using System;

namespace CustomeExceptions
{
    class Program
    {
        //static void Main(string[] args)
        //{
        //    int sayi = 0;
        //    int sayac;

        //    do
        //    {
        //        sayac = 0;
        //        Console.WriteLine("Lütfen bir sayı giriniz : ");
        //        try
        //        {
                   

        //            sayi = int.Parse(Console.ReadLine());
        //            Console.WriteLine("Girilen sayı +5 : " + (sayi + 5));
        //            Console.WriteLine("Devam..");

        //            int bolen = 0;
        //            try
        //            {
        //                Console.WriteLine("Lütfen böleni giriniz");
        //                bolen = int.Parse(Console.ReadLine());
        //            }
        //            catch (Exception)
        //            {
        //                throw;
        //            }
        //            Console.WriteLine(sayi/bolen);
        //        }
        //        catch(DivideByZeroException dbze)
        //        {
        //            Console.WriteLine((dbze.StackTrace);
        //            Console.WriteLine("Tanımsız");
        //            sayac++;
        //        }
        //        catch (ArgumentException)
        //        {

        //            Console.WriteLine("Değer boş olamaz");
        //        }
        //        catch (FormatException ex)
        //        {

        //            Console.WriteLine("Lütfen doğru formatta değer giriniz..");
        //            //Console.WriteLine(ex.Message);
        //            //Console.WriteLine(ex.Source);
        //            //Console.WriteLine(ex.HelpLink);


        //        }
        //        catch (OverflowException)
        //        {

        //            Console.WriteLine("Değer 2,147,483,647 büyük olamaz");
        //        }
        //        catch (Exception)
        //        {

        //            throw;
        //        }


        //    } while (true);

        //}





    }
}
